print("Hello")
name = input("What is your name?")
print(f"Hello {name}")
print("I am going to tell you a joke if you like it or not")
input("")
print("What did the bee say to the sushi")
input("")
print("wasabi")
input()
input(f"Did you like my joke?")
print ("Thanks for your feedback") 