print("Hello")
name=input("What is your name?")
print(f"Hello {name} today you are going to help me make a story")
print("okay lets get started")
input()
animal = input("pick an animal:")
job = input("Give me a job:")
verb = input("give me a plural verb:")
name2 = input("give me a random name:")
print=(f" There once was a/an {animal} named {name2}.")
