print("Hello")
name=input("What is your name?")
print(f"Hello {name}, today you are going to help me make a story!")
print("Okay lets get started")
input()
animal = input("Pick an animal:")
job = input("Give me a job:")
verb = input("Give me a plural verb:")
name2 = input("Give me a random name:")
print(r"___________________________________________")
print(f"There once was a/an {animal} named {name2}.")
print(f"{name2} always {verb} to work")
print(f"They are a {job}.")
print("They love their job!")
print(r"___________________________________________")
input()
print ("Thanks for helping me make a story")
print("Bye!")